# This is a Docker Compose configuration
# intended for development purposes only


services:
  burncloud-docs-db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: burncloud-docs
      MYSQL_ROOT_PASSWORD: 123456qwe!@#
    volumes:
      - ./dev/docker/init.db:/docker-entrypoint-initdb.d
      - ./burncloud_docs_mysql_data:/var/lib/mysql
    networks:
      - nginx-network
    container_name: burncloud-docs-db
  burncloud-docs-app:
    build:
      context: .
      dockerfile: ./dev/docker/Dockerfile
    environment:
      APP_URL: https://docs.burncloud.com
      DB_CONNECTION: mysql
      DB_HOST: burncloud-docs-db
      DB_PORT: 3306
      DB_DATABASE: burncloud-docs
      DB_USERNAME: root
      DB_PASSWORD: 123456qwe!@#
      TEST_DATABASE_URL: mysql://root:123456qwe%21%40%23@burncloud-docs-db/burncloud-docs
      MAIL_DRIVER: smtp
      MAIL_HOST: smtp.exmail.qq.com
      MAIL_PORT: 465
      MAIL_USERNAME: contact@burncloud.com
      MAIL_PASSWORD: 3H59uyWkgJBYpuBH
      MAIL_ENCRYPTION: ssl
    volumes:
      - ./:/app
      - ./dev/docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    entrypoint: /app/dev/docker/entrypoint.app.sh
    extra_hosts:
    - "host.docker.internal:host-gateway"
    networks:
      - nginx-network
    container_name: burncloud-docs-app
  burncloud-docs-node:
    image: node:22-alpine
    working_dir: /app
    user: node
    volumes:
      - ./:/app
    entrypoint: /app/dev/docker/entrypoint.node.sh
    networks:
      - nginx-network
    container_name: burncloud-docs-node

volumes:
  burncloud_docs_mysql_data: {}

networks:
  nginx-network:
    external: true
