# This is a Docker Compose configuration
# intended for development purposes only


services:
  burncloud-docs-db:
    image: mysql:8.4
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./dev/docker/init.db:/docker-entrypoint-initdb.d
      - ./burncloud_docs_mysql_data:/var/lib/mysql
    networks:
      - nginx-network
    container_name: burncloud-docs-db
  burncloud-docs-app:
    build:
      context: .
      dockerfile: ./dev/docker/Dockerfile
    env_file:
      - .env
    environment:
      DB_CONNECTION: mysql
      DB_PORT: 3306
    volumes:
      - ./:/app
      - ./public/dist:/app/public/dist
      - ./node_modules:/app/node_modules
      - ./dev/docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    entrypoint: /app/dev/docker/entrypoint.app.sh
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - nginx-network
    container_name: burncloud-docs-app
  burncloud-docs-node:
    image: node:22-alpine
    working_dir: /app
    user: node
    volumes:
      - ./:/app
      - ./public/dist:/app/public/dist
      - ./node_modules:/app/node_modules
    entrypoint: /app/dev/docker/entrypoint.node.sh
    networks:
      - nginx-network
    container_name: burncloud-docs-node

volumes:
  burncloud_docs_mysql_data: {}

networks:
  nginx-network:
    external: true
